apps/base/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from apps.base import views
from .forms import *
from .views import SignupView, LoginView, profile, update_profile

app_name = 'phone'

urlpatterns = [
    path('', views.base_home, name='base_home'),
    path('base/signup/', SignupView.as_view(), name='base_registration'),
    path('base/login/', LoginView.as_view(redirect_authenticated_user=True, template_name='registration/login.html',
                                          authentication_form=LoginForm), name='base_login'),
    path('base/logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='base_logout'),
    path('profile/', profile, name='users-profile'),
    path('<int:pk>/update-profile/', update_profile, name='update_profile')
]

apps/home/urls.py
from django.urls import path, re_path
from apps.home import views

app_name = 'home'

urlpatterns = [
    # The home page
    path('', views.index, name='home'),
    path('billing/', views.billing, name='billing'),
    path('table/', views.tables, name='tables'),
    path('virtual-reality/', views.virtual_reality, name='virtual_reality'),
    path('EUUjphcxKmD7qf/rtl-section/', views.rtl, name='rtl_section'),
    path('profiles/', views.profiles, name='profile_section')
    # # Matches any html file
    # re_path(r'^.*\.*', views.pages, name='pages'),

]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
import random, string

x = ''.join(random.choices(string.ascii_letters + string.digits, k=60))

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.authentication.urls")),
    path("V8HMZQlXCZCCuvrjpuzEUUjphcxKmD7qffrhJ4s89ejOmIX1dwwl8R9UfFNB/", include("apps.home.urls", namespace='developer')),
    path("", include("apps.base.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/base/models.py
from PIL import Image
from django.db import models
from apps.authentication.models import User


# make profile section here
class Profile(models.Model):
    user = models.OneToOneField(User, blank=True, on_delete=models.CASCADE)

    avatar = models.ImageField(default='redmi.jpg')
    bio = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

    def __str__(self):
        return self.user.username


# create home sliders model
class HomeSliders(models.Model):
    class Meta:
        verbose_name = 'Home Slider'
        verbose_name_plural = 'Home Sliders'

    slider_text = models.CharField(max_length=101)

    def __str__(self):
        return self.slider_text


# create fashion cards
class FashionCards(models.Model):

    class Meta:
        verbose_name = 'Fashion Card'
        verbose_name_plural = 'Fashion Cards'

    image = models.ImageField()
    phone_type = models.CharField(max_length=90)
    price = models.IntegerField(default=50)

    def __str__(self):
        return self.phone_type


# create phone back covers
class PhoneBackCovers(models.Model):

    class Meta:
        verbose_name = 'Phone Back Cover'
        verbose_name_plural = 'Phone Back Covers'

    cover_name = models.CharField(max_length=100)
    cover_price = models.IntegerField(default=5)
    cover_image = models.ImageField()

    def __str__(self):
        return self.cover_name


# create phone accessories
class PhoneAccessories(models.Model):

    class Meta:
        verbose_name = 'Phone Accessories'
        verbose_name_plural = 'Phone Accessories'

    accessories_name = models.CharField(max_length=100)
    accessories_price = models.IntegerField(default=4)
    accessories_image = models.ImageField()

    def __str__(self):
        return self.accessories_name

apps/home/models.py
from django.db import models


class DashboardTopCards(models.Model):
    
    class Meta:
        verbose_name = 'Dashboard Top'
        verbose_name_plural = 'Dashboard Top Cards'

    main_theme = models.CharField(max_length=100)
    money = models.FloatField(default=100)
    users = models.FloatField(default=100)
    new_clients = models.FloatField(default=100)
    sales = models.FloatField(default=100)

    def __str__(self):
        return self.main_theme

apps/base/forms.py
import phonenumbers
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget

from .models import Profile

User = get_user_model()


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(
        required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.IntegerField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }), required=True)
    work_phone = forms.IntegerField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }), required=True)
    address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Andijon shaxri, Seramov Ko'chasi",
        'class': 'form-control',
    }), required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'phone', 'first_name', 'last_name', 'work_phone', 'address']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(
        attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'rows': 5
    }))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']


# register form here
class RegisterForm(UserCreationForm):
    # fields we want to include and customize in our form
    first_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'First Name',
            'class': 'form-control',
        }))
    last_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Last Name',
            'class': 'form-control',
        }))
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Username',
            'class': 'form-control',
        }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={
                                 'placeholder': 'Email',
                                 'class': 'form-control',
                             }))
    phone = forms.IntegerField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }), required=True)
    work_phone = forms.IntegerField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }), required=True)
    address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Andijon shaxri, Seramov Ko'chasi",
        'class': 'form-control',
    }), required=False)
    work_field = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Ex: Teacher",
        'class': 'form-control',
    }), required=False)
    bio = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Bio",
        'class': 'form-control',
    }), required=False)
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(
                                    attrs={
                                        'placeholder': 'Password',
                                        'class': 'form-control',
                                        'data-toggle': 'password',
                                        'id': 'password',
                                    }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(
                                    attrs={
                                        'placeholder': 'Confirm Password',
                                        'class': 'form-control',
                                        'data-toggle': 'password',
                                        'id': 'password',
                                    }))

    class Meta:
        model = User
        fields = [
            'first_name', 'last_name', 'username', 'email', 'phone', 'work_phone', 'address', 'work_field', 'bio', 'password1',
            'password2'
        ]


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']

apps/base/views.py
import phonenumbers
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, reverse
from django.views.generic import *

from .forms import *
from .models import *


# base home function here
def base_home(request):
    sliders = HomeSliders.objects.all()
    fashion_cards = FashionCards.objects.all()
    phone_cover = PhoneBackCovers.objects.all()
    phone_accessories = PhoneAccessories.objects.all()
    context = {
        "sliders": sliders,
        "fashion_cards": fashion_cards,
        "phone_cover": phone_cover,
        "phone_accessories": phone_accessories
    }
    return render(request, 'base/pages/home.html', context)


# create sign up view
class SignupView(CreateView):
    template_name = 'registration/signup.html'
    initial = {'key': 'value'}
    form_class = RegisterForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')

            return redirect(to='/')

        return render(request, self.template_name, {'form': form})


# create login view here
class LoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # set session expiry to 0 seconds. So it will automatically close the session after the browser is closed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/cookie to be saved.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(LoginView, self).form_valid(form)


# create user profile
@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST,
                                         request.FILES,
                                         instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users-profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'base/pages/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
def update_profile(request, pk):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST,
                                         request.FILES,
                                         instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect('/profile/')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'base/pages/update_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

apps/home/views.py
from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from .models import DashboardTopCards


@login_required(login_url="/login/")
def index(request):
    cards = DashboardTopCards.objects.all()
    context = {'segment': 'index', 'cards': cards}

    html_template = loader.get_template('home/index.html')
    return HttpResponse(html_template.render(context, request))


# @login_required(login_url="/login/")
# def pages(request):
#     context = {}
#     try:
#
#         load_template = request.path.split('/')[-1]
#
#         if load_template == 'admin':
#             return HttpResponseRedirect(reverse('admin:index'))
#         context['segment'] = load_template
#
#         html_template = loader.get_template('home/' + load_template)
#         return HttpResponse(html_template.render(context, request))
#
#     except template.TemplateDoesNotExist:
#
#         html_template = loader.get_template('home/page-404.html')
#         return HttpResponse(html_template.render(context, request))
#
#     except:
#         html_template = loader.get_template('home/page-500.html')
#         return HttpResponse(html_template.render(context, request))

# tables
def tables(request):
    return render(request, 'home/tables.html')


# virtual reality
def virtual_reality(request):
    return render(request, 'home/virtual-reality.html')


# RTL section
def rtl(request):
    return render(request, 'home/rtl.html')


# profiles section
def profiles(request):
    return render(request, 'home/profile.html')


@login_required(login_url="/login/")
def billing(request):
    return render(request, 'home/billing.html')

apps/templates/base/pages/home.html
{% extends 'base/layout/base.html' %}
{% load static  %}
{% block content %}
    <div class="banner_bg_main">
         <!-- logo section start -->
         <div class="logo_section">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="logo"><a style="font-size: 60px; color: white; font-weight: bold;" href="#">MobileLand</a></div>
                  </div>
               </div>
            </div>
         </div>
         <!-- logo section end -->
         <!-- header section start -->
         <div class="header_section">
            <div class="container">
               <div class="containt_main">
                  <div id="mySidenav" class="sidenav">
                     <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                     <a href="#">Home</a>
                     <a href="#">Fashion</a>
                     <a href="#">Electronic</a>
                     <a href="#">Jewellery</a>
                  </div>
                  <span class="toggle_icon" onclick="openNav()"><img src="{%  static 'images/toggle-icon.png' %}"></span>
                  <div class="dropdown">
                     <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All Category
                     </button>
                     <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                     </div>
                  </div>
                  <div class="main">
                     <!-- Another variation with a button -->
                     <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search this blog">
                        <div class="input-group-append">
                           <button class="btn btn-secondary" type="button" style="background-color: #f26522; border-color:#f26522 ">
                           <i class="fa fa-search"></i>
                           </button>
                        </div>
                     </div>
                  </div>
                  <div class="header_box">
                     <div class="lang_box ">
                        <a href="#" title="Language" class="nav-link" data-toggle="dropdown" aria-expanded="true">
                        <img src="{% static 'images/flag-uk.png' %}" alt="flag" class="mr-2 " title="United Kingdom"> English <i class="fa fa-angle-down ml-2" aria-hidden="true"></i>
                        </a>
                         <div class="dropdown-menu ">
                             <a href="#" class="dropdown-item">
                                 <img src="{% static 'images/flag-france.png' %}" class="mr-2" alt="flag">
                                 French
                             </a>
                         </div>
                     </div>
                      <div class="login_menu">
                          <ul>
                              {% if request.user.is_authenticated %}
                                  <li><a href="{% url 'phone:base_logout' %}">
                                      <span class="pl-1">Logout</span></a>
                                  </li>
                                  <li><a href="{% url 'phone:users-profile' %}">
                                      <span class="pl-1">Profile</span></a>
                                  </li>
                                  <li><a href="#">
                                      <span class="pl-1">{{ request.user.username }}</span>
                                  </a></li>
                              {% else %}
                                  <li><a href="{% url 'phone:base_login' %}">
                                      <span class="pl-1">Login</span></a>
                                  </li>
                              {% endif %}
                              {% if not request.user.is_authenticated %}
                                  <li><a href="{% url 'phone:base_registration' %}">
                                      {#<i class="fa-solid fa-arrow-up-right-from-square"></i>#}
                                      <span class="pl-1">Sign Up</span></a>
                                  </li>
                              {% endif %}
                          </ul>
                      </div>
                  </div>
               </div>
            </div>
         </div>
        <!-- header section end -->
         <!-- banner section start -->
         <div class="banner_section layout_padding">
            <div class="container">
                <div id="my_slider" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <div class="row">
                                <div class="col-sm-12">
                                    <h1 class="banner_taital">Cheapest prices to buy</h1>
                                    <div class="buynow_bt"><a href="#">Buy Now</a></div>
                                </div>
                            </div>
                        </div>
                        {% for slider in sliders %}
                        <div class="carousel-item">
                            <div class="row">
                                <div class="col-sm-12">
                                    <h1 class="banner_taital" style="width: 800px !important; margin-left: auto; margin-right: auto;">{{ slider.slider_text }}</h1>
                                    <div class="buynow_bt"><a href="#">Buy Now</a></div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>
            </div>
         </div>

        <!-- fashion section start -->
        {% include 'base/includes/fashion.html' %}
        <!-- fashion section ends -->
    </div>
    <!-- electronic section start -->
    {% include 'base/includes/electronics.html' %}
    <!-- electronic section end -->
    <!-- jewellery  section start -->
    {% include 'base/includes/jewelry.html' %}
    <!-- jewellery  section end -->

{% endblock content %}