apps/base/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from apps.base import views
from .forms import *
from .views import SignupView, LoginView, profile, update_profile

app_name = 'phone'

urlpatterns = [
    path('', views.base_home, name='base_home'),
    path('base/signup/', SignupView.as_view(), name='base_registration'),
    path('base/login/', LoginView.as_view(redirect_authenticated_user=True, template_name='registration/login.html',
                                          authentication_form=LoginForm), name='base_login'),
    path('base/logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='base_logout'),
    path('profile/', profile, name='users-profile'),
    path('<int:pk>/update-profile/', update_profile, name='update_profile')
]

apps/home/urls.py
from django.urls import path, re_path
from apps.home import views

app_name = 'home'

urlpatterns = [
    # The home page
    path('', views.index, name='home'),
    path('billing/', views.billing, name='billing'),
    path('table/', views.tables, name='tables'),
    path('virtual-reality/', views.virtual_reality, name='virtual_reality'),
    path('EUUjphcxKmD7qf/rtl-section/', views.rtl, name='rtl_section'),
    path('profiles/', views.profiles, name='profile_section')
    # # Matches any html file
    # re_path(r'^.*\.*', views.pages, name='pages'),

]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
import random, string

x = ''.join(random.choices(string.ascii_letters + string.digits, k=60))

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.authentication.urls")),
    path("V8HMZQlXCZCCuvrjpuzEUUjphcxKmD7qffrhJ4s89ejOmIX1dwwl8R9UfFNB/", include("apps.home.urls", namespace='developer')),
    path("", include("apps.base.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/base/models.py
from PIL import Image
from django.db import models
from apps.authentication.models import User


# make profile section here
class Profile(models.Model):
    user = models.OneToOneField(User, blank=True, on_delete=models.CASCADE)

    avatar = models.ImageField(default='redmi.jpg')
    bio = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

    def __str__(self):
        return self.user.username


# create home sliders model
class HomeSliders(models.Model):
    class Meta:
        verbose_name = 'Home Slider'
        verbose_name_plural = 'Home Sliders'

    slider_text = models.CharField(max_length=101)

    def __str__(self):
        return self.slider_text


# create fashion cards
class FashionCards(models.Model):

    class Meta:
        verbose_name = 'Fashion Card'
        verbose_name_plural = 'Fashion Cards'

    image = models.ImageField()
    phone_type = models.CharField(max_length=90)
    price = models.IntegerField(default=50)

    def __str__(self):
        return self.phone_type


# create phone back covers
class PhoneBackCovers(models.Model):

    class Meta:
        verbose_name = 'Phone Back Cover'
        verbose_name_plural = 'Phone Back Covers'

    cover_name = models.CharField(max_length=100)
    cover_price = models.IntegerField(default=5)
    cover_image = models.ImageField()

    def __str__(self):
        return self.cover_name


# create phone accessories
class PhoneAccessories(models.Model):

    class Meta:
        verbose_name = 'Phone Accessories'
        verbose_name_plural = 'Phone Accessories'

    accessories_name = models.CharField(max_length=100)
    accessories_price = models.IntegerField(default=4)
    accessories_image = models.ImageField()

    def __str__(self):
        return self.accessories_name

apps/base/forms.py
import phonenumbers
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget

from .models import Profile

User = get_user_model()


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(
        required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.IntegerField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }), required=True)
    work_phone = forms.IntegerField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }), required=True)
    address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Andijon shaxri, Seramov Ko'chasi",
        'class': 'form-control',
    }), required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'phone', 'first_name', 'last_name', 'work_phone', 'address']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(
        attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'rows': 5
    }))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']


# register form here
class RegisterForm(UserCreationForm):
    # fields we want to include and customize in our form
    first_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'First Name',
            'class': 'form-control',
        }))
    last_name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Last Name',
            'class': 'form-control',
        }))
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Username',
            'class': 'form-control',
        }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={
                                 'placeholder': 'Email',
                                 'class': 'form-control',
                             }))
    phone = forms.IntegerField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }), required=True)
    work_phone = forms.IntegerField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }), required=True)
    address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Andijon shaxri, Seramov Ko'chasi",
        'class': 'form-control',
    }), required=False)
    work_field = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Ex: Teacher",
        'class': 'form-control',
    }), required=False)
    bio = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Bio",
        'class': 'form-control',
    }), required=False)
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(
                                    attrs={
                                        'placeholder': 'Password',
                                        'class': 'form-control',
                                        'data-toggle': 'password',
                                        'id': 'password',
                                    }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(
                                    attrs={
                                        'placeholder': 'Confirm Password',
                                        'class': 'form-control',
                                        'data-toggle': 'password',
                                        'id': 'password',
                                    }))

    class Meta:
        model = User
        fields = [
            'first_name', 'last_name', 'username', 'email', 'phone', 'work_phone', 'address', 'work_field', 'bio', 'password1',
            'password2'
        ]


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']

apps/base/views.py
import phonenumbers
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, reverse
from django.views.generic import *

from .forms import *
from .models import *


# base home function here
def base_home(request):
    sliders = HomeSliders.objects.all()
    fashion_cards = FashionCards.objects.all()
    phone_cover = PhoneBackCovers.objects.all()
    phone_accessories = PhoneAccessories.objects.all()
    context = {
        "sliders": sliders,
        "fashion_cards": fashion_cards,
        "phone_cover": phone_cover,
        "phone_accessories": phone_accessories
    }
    return render(request, 'base/pages/home.html', context)


# create sign up view
class SignupView(CreateView):
    template_name = 'registration/signup.html'
    initial = {'key': 'value'}
    form_class = RegisterForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')

            return redirect(to='/')

        return render(request, self.template_name, {'form': form})


# create login view here
class LoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # set session expiry to 0 seconds. So it will automatically close the session after the browser is closed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/cookie to be saved.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(LoginView, self).form_valid(form)


# create user profile
@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST,
                                         request.FILES,
                                         instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users-profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'base/pages/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
def update_profile(request, pk):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST,
                                         request.FILES,
                                         instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect('/profile/')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'base/pages/update_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

apps/templates/base/includes/electronics.html
{% load static %}
<!-- electronic section start -->
<div class="fashion_section">
    <div id="electronic_main_slider" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container">
                    <h1 class="fashion_taital">Phone laminats</h1>
                    <div class="fashion_section_2">
                        <div class="row">
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main">
                                    <h4 class="shirt_text">Deep wood</h4>
                                    <p class="price_text">Start Price <span style="color: #262626;">$ 3</span></p>
                                    <div class="electronic_img"><img src="{% static 'images/laminate-removebg-preview.png' %}"></div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a href="#">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="#">See More</a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main">
                                    <h4 class="shirt_text">Most wraps</h4>
                                    <p class="price_text">Start Price <span style="color: #262626;">$ 5</span></p>
                                    <div class="electronic_img"><img src="{% static 'images/laminate3-removebg-preview.png' %}"></div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a href="#">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="#">See More</a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main">
                                    <h4 class="shirt_text">Flag types</h4>
                                    <p class="price_text">Start Price <span style="color: #262626;">$ 4</span></p>
                                    <div class="electronic_img"><img style="height: 300px;" src="{% static 'images/laminate2-removebg-preview.png' %}"></div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a href="#">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="#">See More</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <h1 class="fashion_taital">Electronic</h1>
                    <div class="fashion_section_2">
                        <div class="row">
                            {% for cover in phone_cover %}
                                <div class="col-lg-4 col-sm-4">
                                    <div class="box_main">
                                        <h4 class="shirt_text">{{ cover.cover_name }}</h4>
                                        <p class="price_text">Start Price <span
                                                style="color: #262626;">$ {{ cover.cover_price }}</span></p>
                                        <div class="electronic_img"><img src="{{ cover.cover_image.url }}">
                                        </div>
                                        <div class="btn_main">
                                            <div class="buy_bt"><a href="#">Buy Now</a></div>
                                            <div class="seemore_bt"><a href="#">See More</a></div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#electronic_main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
        </a>
        <a class="carousel-control-next" href="#electronic_main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
        </a>
    </div>
</div>
<!-- electronic section end -->

apps/templates/base/includes/fashion.html
{% load static %}
<style>
    .box_main {
        cursor: pointer;
    }
    .second_img {
        margin-top: 20px;
    }
    .box_main:hover img {
        transform: scale(1.1);
    }
</style>
<!-- fashion section start -->
<div class="fashion_section">
    <div id="main_slider" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container">
                    <h1 class="fashion_taital" style="color: white;">Samsung phones</h1>
                    <div class="fashion_section_2">
                        <div class="row">
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main">
                                    <h4 class="shirt_text">Samsung a31</h4>
                                    <p class="price_text">Price <span style="color: #262626;">$ 210</span></p>
                                    <div class="tshirt_img"><img src="{% static 'images/samsung-removebg-preview.png' %}"></div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a href="#">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="#">See More</a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main">
                                    <h4 class="shirt_text">Samsung a50</h4>
                                    <p class="price_text">Price <span style="color: #262626;">$ 350</span></p>
                                    <div class="tshirt_img"><img src="{% static 'images/samsung_a50-removebg-preview.png' %}"></div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a href="#">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="#">See More</a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main">
                                    <h4 class="shirt_text">Samsung a90</h4>
                                    <p class="price_text">Price <span style="color: #262626;">$ 620</span></p>
                                    <div class="tshirt_img"><img class="second_img" width="260" src="{% static 'images/samsung_a91-removebg-preview.png' %}">
                                    </div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a href="#">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="#">See More</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <h1 class="fashion_taital" style="color: white!important;">Xiomi redmi phones</h1>
                    <div class="fashion_section_2">
                        <div class="row">
                            {% for card in fashion_cards %}
                                <div class="col-lg-4 col-sm-4">
                                    <div class="box_main">
                                        <h4 class="shirt_text">{{ card.phone_type }}</h4>
                                        <p class="price_text">Price <span
                                                style="color: #262626;">$ {{ card.price }}</span></p>
                                        <div class="tshirt_img"><img src="{{ card.image.url }}"></div>
                                        <div class="btn_main">
                                            <div class="buy_bt"><a href="#">Buy Now</a></div>
                                            <div class="seemore_bt"><a href="#">See More</a></div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
        </a>
        <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
        </a>
    </div>
</div>
<!-- fashion section end -->

apps/templates/base/includes/footer.html
{% load static %}
<!-- footer section start -->
<div class="footer_section layout_padding">
    <div class="container">
        <div class="footer_logo"><a style="font-size: 60px; color: white; font-weight: bold;" href="#">MobileLand</a></div>
        <div class="input_bt">
            <input type="text" class="mail_bt" placeholder="Your Email" name="Your Email">
            <span class="subscribe_bt" id="basic-addon2"><a href="#">Subscribe</a></span>
        </div>
        <div class="footer_menu">
            <ul>
                <li><a href="#">Best Sellers</a></li>
                <li><a href="#">Gift Ideas</a></li>
                <li><a href="#">New Releases</a></li>
                <li><a href="#">Today's Deals</a></li>
                <li><a href="#">Customer Service</a></li>
            </ul>
        </div>
        <div class="location_main">Help Line Number : <a href="#">+998931065607</a></div>
    </div>
</div>
<!-- footer section end -->
<!-- copyright section start -->
<div class="copyright_section">
    <div class="container">
        <p class="copyright_text">© 2022 All Rights Reserved. Created by <a href="#">Khusan Akhmedov</a></p>
    </div>
</div>
<!-- copyright section end -->

apps/templates/base/includes/jewelry.html
{% load static %}
<!-- jewellery  section start -->
<div class="jewellery_section">
    <div id="jewellery_main_slider" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container">
                    <h1 class="fashion_taital">Pricable accessories</h1>
                    <div class="fashion_section_2">
                        <div class="row">
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main">
                                    <h4 class="shirt_text">Type C-6fts</h4>
                                    <p class="price_text">Start Price <span style="color: #262626;">$ 7</span></p>
                                    <div class="jewellery_img"><img src="{% static 'images/charger-removebg-preview.png' %}"></div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a href="#">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="#">See More</a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main">
                                    <h4 class="shirt_text">China EU Plug</h4>
                                    <p class="price_text">Start Price <span style="color: #262626;">$ 5</span></p>
                                    <div class="jewellery_img"><img src="{% static 'images/charger3-removebg-preview.png' %}"></div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a href="#">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="#">See More</a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-sm-4">
                                <div class="box_main">
                                    <h4 class="shirt_text">Charger RT5s</h4>
                                    <p class="price_text">Start Price <span style="color: #262626;">$ 9</span></p>
                                    <div class="jewellery_img"><img src="{% static 'images/charger2-removebg-preview.png' %}"></div>
                                    <div class="btn_main">
                                        <div class="buy_bt"><a href="#">Buy Now</a></div>
                                        <div class="seemore_bt"><a href="#">See More</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <h1 class="fashion_taital">Phone Accessories</h1>
                    <div class="fashion_section_2">
                        <div class="row">
                            {% for phone_accessory in phone_accessories %}
                                <div class="col-lg-4 col-sm-4">
                                    <div class="box_main">
                                        <h4 class="shirt_text">{{ phone_accessory.accessories_name }}</h4>
                                        <p class="price_text">Start Price <span
                                                style="color: #262626;">$ {{ phone_accessory.accessories_price }}</span></p>
                                        <div class="jewellery_img"><img src="{{ phone_accessory.accessories_image.url }}">
                                        </div>
                                        <div class="btn_main">
                                            <div class="buy_bt"><a href="#">Buy Now</a></div>
                                            <div class="seemore_bt"><a href="#">See More</a></div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#jewellery_main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
        </a>
        <a class="carousel-control-next" href="#jewellery_main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
        </a>
        <div class="loader_main">
            <div class="loader"></div>
        </div>
    </div>
</div>
<!-- jewellery  section end -->

apps/templates/base/includes/navbar.html
<div class="banner_bg_main">
<div class="container">
            <div class="header_section_top">
               <div class="row">
                   <div class="col-sm-12">
                     <div class="custom_menu">
                        <ul>
                           <li><a href="{% url 'phone:base_home' %}">Home</a></li>
                           <li><a href="#">Best Sellers</a></li>
                           <li><a href="#">Gift Ideas</a></li>
                           <li><a href="#">New Releases</a></li>
                           <li><a href="#">Customer Service</a></li>
                            {% if request.user.is_organiser %}
                                <li><a href="{% url 'developer:home' %}">Developer</a></li>
                            {% endif %}
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
    </div>